---
- name: install nginx
  apt: name=nginx state=present
  sudo: yes

- name: copy nginx.conf to the server
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes

- name: delete default virtualhost
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes

- name: add agameoftags site-available
  template: src=agameoftags.conf.j2 dest=/etc/nginx/sites-available/agameoftags.conf
  sudo: yes

- name: link agameoftags site-enabled
  file: path=/etc/nginx/sites-enabled/agameoftags src=/etc/nginx/sites-available/agameoftags.conf state=link
  sudo: yes