#!/usr/bin/env rake

require 'droplet_kit'
require 'securerandom'
require 'yaml'

task :default do
  Rake::Task["provisioning:add_secret_key"].invoke
  Rake::Task["provisioning:create_vps"].invoke
  Rake::Task["provisioning:bootstrap_vps"].invoke
  Rake::Task["provisioning:setup_vps"].invoke
end

namespace :agameoftags do
  task :update do
    system 'ansible-playbook playbooks/upload_latest.yml -i playbooks/hosts -K'
  end
end

namespace :provisioning do
  task :add_secret_key do
    secret = SecureRandom.hex(64)
    system "sed -i '' 's/XXX/#{secret}/' ./playbooks/roles/deploy/templates/secrets.yml.j2"
  end

  task :create_vps do
    puts "Creating a new DigitalOcean droplet"
    droplets = []
    access_token = YAML.load(File.open("./playbooks/digital_ocean_token.yml"))
    client       = DropletKit::Client.new(access_token: access_token['digital_ocean'])
    my_ssh_keys  = client.ssh_keys.all.collect {|key| key.fingerprint}
    droplet = DropletKit::Droplet.new(name: 'agameoftags',
                                      region: 'nyc2',
                                      image: 'ubuntu-14-04-x64',
                                      size: '1gb',
                                      ssh_keys: my_ssh_keys)
    client.droplets.create(droplet)
    system "cp ./playbooks/hosts.example ./playbooks/hosts"
  end

  task :bootstrap_vps do
    puts "\nbootstrapping up the VPS"
    system 'ansible-playbook playbooks/bootstrap.yml -i playbooks/hosts'
  end

  task :setup_vps do
    puts "\nSetting up the VPS"
    system 'ansible-playbook playbooks/setup.yml -i playbooks/hosts -K'
  end
end