- name: Fetch latest git changes
  git: repo={{ git_repository }} dest={{ app_directory }} force=yes update=yes

- name: bundle install
  command: bash -lc "cd {{ app_directory }} && bundle install --without development test"
  retries: 3
  delay: 10

- name: run migrations
  command: bash -lc "RAILS_ENV=production bundle exec rake db:migrate" chdir={{app_directory}}

- name: precompile assets
  command: bash -lc "RAILS_ENV=production bundle exec rake assets:precompile" chdir={{app_directory}}

- name: get pid id
  command: cat {{ app_directory }}tmp/puma/pid
  register: pid_id
  ignore_errors: True

- name: attempt restarting puma
  command: kill -s SIGUSR2 {{ pid_id.stdout }}
  notify: restart nginx
  register: result
  ignore_errors: True

- name: attempt starting puma
  command: bash -lc "RAILS_ENV=production bundle exec puma -C config/puma/production.rb -d" chdir={{ app_directory}}
  notify: restart nginx
  when: result|failed
  ignore_errors: yes

- name: get sidekiq pid
  command: cat {{ app_directory }}tmp/pids/sidekiq.pid
  register: sidekiq_pid

- name: stop accepting sidekiq jobs
  command: bash -lc "kill -USR1 {{sidekiq_pid.stdout}}"

- name: stop sidekiq
  command: bash -lc "kill -TERM {{sidekiq_pid.stdout}}"

- name: start sidekiq
  command: bash -lc "bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -e production" chdir={{app_directory}}